add `iconName` to `BezierSource` migration to codemod
channel-io/bezier-react pull request #1418
Opened 2023-06-12 06:58 UTC by yangwooseong

## Self Checklist

- [x] I wrote a PR title in **English**.
- [x] I added an appropriate **label** to the PR.
- [x] I wrote a commit message in **English**.
- [x] I wrote a commit message according to [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] [I added the appropriate **changeset**](https://github.com/channel-io/bezier-react/blob/main/CONTRIBUTING.md#add-a-changeset) for the changes.
- [ ] [Component] I wrote **a unit test** about the implementation.
- [ ] [Component] I wrote **a storybook document** about the implementation.
- [ ] [Component] I tested the implementation in **various browsers**.
  - Windows: Chrome, Edge, (Optional) Firefox
  - macOS: Chrome, Edge, Safari, (Optional) Firefox
- [ ] [*New* Component] I added my username to the correct directory in the `CODEOWNERS` file.

## Related Issue

- https://github.com/channel-io/bezier-react/issues/762

## Summary

- 다음과 같이 `iconName` 에서 `BezierIcon` 으로 마이그레이션해주는 옵션을 `codemod` 에 추가합니다.

- As-is
```typescript
import React from 'react'

export default function CancelButton() {
  return (
    <Button
      leftContent="arrow-left"
      rightContent="all"
      styleVariant={ButtonStyleVariant.Primary}
      text={translate('common.save')}
      disabled={disabled}
      onClick={handleSave}
    />
  )
}
```
- To-be

```typescript
import React from 'react'
import { ArrowLeftIcon, AllIcon } from '@channel.io/bezier-icons'

export default function CancelButton() {
  return (
    <Button
      leftContent={ArrowLeftIcon}
      rightContent={AllIcon}
      styleVariant={ButtonStyleVariant.Primary}
      text={translate('common.save')}
      disabled={disabled}
      onClick={handleSave}
    />
  )
}
```

## Details

- 이런 마이그레이션 로직이 필요한 이유는 https://github.com/channel-io/bezier-react/issues/762 를 참고해주세요.

- 마이그레이션 로직은 기본적으로 `component` 이름과 `attributes` 를 받아서 마이그레이션 대상을 찾은 뒤, 적절히 import 구문을 추가하는 흐름입니다. import 를 추가할 때는 `bezier-react` import 가 있다면 바로 뒤에, 없다면 `react` import 바로 뒤에 넣습니다. 

- 이 마이그레이션은 다음과 같은 상황에서는 적용되지 않음에 주의해야 합니다.
  - attribute 를 동적으로 가져와서 사용할 때 e.g. `leftContent={IconByCountry['KR']}`
  - styled-component 에서 스타일링 하여 사용할 때
  - 의도치 않은 네이밍으로 사용되고 있는 컴포넌트일 때 e.g. 버튼 컴포넌트이지만 네이밍에 `Button` 을 포함하지 않는 경우
 

## Breaking change or not (Yes/No)

- No

## References

- https://github.com/channel-io/bezier-react/pull/1382

2023-06-14 08:08 UTC, sungik-choi approved these changes

2023-06-14 08:10 UTC, sungik-choi commented on .changeset/pink-ladybugs-tan.md
> +"@channel.io/bezier-codemod": patch
새로운 기능이 추가되었으므로 minor 버전을 올리는 게 적절할 거 같습니다!

2023-06-14 08:13 UTC, sungik-choi commented
👍 Transformers 직접 만들어보시면서 개선 포인트 등을 느끼신 게 있는지 궁금합니다. 이슈로 만들어서 챙겨보려고 해요

2023-06-15 05:27 UTC, yangwooseong commented
> 

일단 레퍼런스가 많이 쌓이면 좋을 것 같다는 생각입니다! 사실 처음 만드는 것이기도 해서 Transformer 를 만드는 시간 대비 사용해서 아끼는 시간이 크다는 생각은 안들었는데, 레퍼런스가 좀 쌓이면 만드는 시간이 확실히 더 줄어들 것 같아요. 저도 공식문서 API 를 보고 잘 이해안되는 것이 많아서 에드가 짜주신 코드랑 gpt 에 많이 의존했습니다

그리고 커멘트 주신대로 공통 유틸을 분리해봐도 좋을 것 같네요. import 문을 찾거나 migration 해야햐는 컴포넌트 찾는 것은 앞으로 많이 쓰일 것 같아서, 많이 쓰일만한 코드들은 ts-morph API 를 몰라도 사용할 수 있게하면 좋을 것 같습니다.

2023-06-15 06:05 UTC, sungik-choi requested changes

2023-06-15 06:05 UTC, sungik-choi commented on .changeset/perfect-tips-sleep.md
> +---
changeset 하나만 생성해주세요~! 기존 changeset을 열어서 마크다운 내용을 변경하시면 됩니다.

2023-06-15 06:06 UTC, yangwooseong commented on .changeset/perfect-tips-sleep.md
> +---
아하.. 넵

2023-06-15 06:09 UTC, sungik-choi approved these changes

2023-06-15 06:14 UTC, merged

2023-06-16 08:06 UTC, yangwooseong commented
> > 
> 
> 일단 레퍼런스가 많이 쌓이면 좋을 것 같다는 생각입니다! 사실 처음 만드는 것이기도 해서 Transformer 를 만드는 시간 대비 사용해서 아끼는 시간이 크다는 생각은 안들었는데, 레퍼런스가 좀 쌓이면 만드는 시간이 확실히 더 줄어들 것 같아요. 저도 공식문서 API 를 보고 잘 이해안되는 것이 많아서 에드가 짜주신 코드랑 gpt 에 많이 의존했습니다
> 
> 그리고 커멘트 주신대로 공통 유틸을 분리해봐도 좋을 것 같네요. import 문을 찾거나 migration 해야햐는 컴포넌트 찾는 것은 앞으로 많이 쓰일 것 같아서, 많이 쓰일만한 코드들은 ts-morph API 를 몰라도 사용할 수 있게하면 좋을 것 같습니다.

추가로, 패키지안에서 cli 로 변환될 수 있는 mock 코드가 있으면 좋겠어요. 그러면 cli 를 수정하거나 할 떄 직접 테스트해 볼 수 있어서 편하지 않을까요? 그리고 file 경로 지정하기 전(혹은 후)에 마이그레이션할 컴포넌트와 attribute 등 입력할 수 있는 스텝이 추가되면 좋겠네요 (지금 icon-name-to-bezier-icon 에서 넣어주는 meta 를 사용자에게 입력받을 수 있도록). 그래서 여기서 컴포넌트 상관없이 하겠다, 아니면 특정 컴포넌트만 하겠다 선택할 수 있게!