Migrate `Avatar`, `AvatarGroup` component with scss
channel-io/bezier-react pull request #1871
Opened 2024-01-02 08:06 UTC by yangwooseong

## Self Checklist

- [x] I wrote a PR title in **English** and added an appropriate **label** to the PR.
- [x] I wrote the commit message in **English** and to follow [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I [added the **changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) about the changes that needed to be released. (or didn't have to)
- [x] I wrote or updated **documentation** related to the changes. (or didn't have to)
- [x] I wrote or updated **tests** related to the changes. (or didn't have to)
- [x] I tested the changes in various browsers. (or didn't have to)
  - Windows: Chrome, Edge, (Optional) Firefox
  - macOS: Chrome, Edge, Safari, (Optional) Firefox

## Related Issue

- #1733 

## Summary

- `Avatar`, `AvatarGroup` 컴포넌트를 scss 로 마이그레이션 합니다.
- JSDoc 에 example code 를 추가합니다.

## Details

- `AvatarGroup` 컴포넌트의 경우 `HStack`이 margin이 아닌 gap으로 간격을 주고 있어서 `HStack`을 사용할 수 없었습니다. spacing 은 음수를 받을 수 있는데 gap으로는 음수를 처리할 수 없기 때문입니다. 

### Breaking change? (Yes/No)

- Yes. 이제 `Avatar`컴포넌트의 `interpolation`속성이 없어집니다.

2024-01-03 05:50 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
> + * `Avatar` is a component for representing some profile image.
👍

2024-01-03 05:50 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
>                backgroundColor="bgtxt-absolute-black-lightest"
이 PR과 다른 컨텍스트인데, 여길 보니 LayoutProps.bgColor도 일관성을 위해 backgroundColor로 바꾸는 게 나으려나 싶네요 🤔

2024-01-03 05:50 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
>          '--b-avatar-group-size': px(size),
향후엔 AvatarSize도 number에서 string 타입으로 바꾸면 좋겠네요. 지금은 (컴파일 에러만 무시하면) number를 그대로 받아서 스타일링할 수 있다보니 `size={100 as AvatatSize}` 같은 식으로 타입 단언해서 강제로 사이즈를 정해진 규격 외로 사용하는 케이스들이 데스크에 몇 있습니다...ㅋㅋ

2024-01-03 05:51 UTC, sungik-choi requested changes

2024-01-03 05:51 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
> +          showBorder && 'bordered',
```suggestion
          showBorder && styled.bordered
```

2024-01-03 05:57 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    &.bordered[data-state="enabled"] {
```suggestion
    &:where(.bordered:where([data-state="enabled"])) {
```

큰 의미는 없겠지만 이렇게도 가능하겠네요.

2024-01-03 06:20 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
>          '--b-avatar-group-size': px(size),
enum -> string literal 로 바꿀 때 string ('20', '24', 등등) 으로 바꾸면 될거같아요!

2024-01-03 06:35 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
> +          showBorder && 'bordered',
스토리북으로 테스트 하면 스타일이 되길래 제가 오해했네요. 스타일이 되는 대신 hash 값이 아닌 plain text가 classname으로 들어가지는 문제가 있어서 변경하겠습니다.

2024-01-03 06:47 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
>                backgroundColor="bgtxt-absolute-black-lightest"
동의합니다!

2024-01-03 09:24 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
이제 reset css에 들어있을거라 제거해도 괜찮을 거 같은데, 확인해봐주실 수 있나요?

2024-01-03 09:24 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
>    } as React.CSSProperties), [size])
이 스타일도 클래스로 미리 정의해둘 수 있을 거 같아요. (AvatarSize가 string이 된다면 동작하지 않게 될 코드이기도 함)

2024-01-03 09:24 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
>          borderRadius={`${AVATAR_BORDER_RADIUS_PERCENTAGE}%`}
```tsx
const token = useToken()
token.global.radius['radius-42-p']
```

이 PR 컨텍스트랑 약간 다른데, 이제 이 값으로 바꿀 수도 있습니다

2024-01-03 09:24 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
>                  '--b-avatar-group-ellipsis-mr': px(getProperEllipsisCountMarginRight(size)),
이 값도 size variant에 기반하므로 미리 클래스로 정의해두면 좋을 거 같아요

2024-01-04 02:18 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
아 reest layer가 있었군요. 그런데 reset layer가 전역 스타일을 변경하는 것 같은데 이거는 문제가 안될까요? 스토리북같은 사용처에서 라디오 버튼이 안보이는 사이드 이펙트가 있습니다. 

<img width="997" alt="image" src="https://github.com/channel-io/bezier-react/assets/28595102/2f2c9433-0302-473a-a741-73935d14da92">

2024-01-04 03:19 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
html 요소의 스타일을 재설정하는 작업이 대개 프로젝트별로 반복되기때문에 이번에 베지어에 reset css를 포함해서 프로젝트별 스타일 중복을 줄이고자 했어요. 기본 html 요소를 사용하는 케이스가 거의 없는데, 스토리북에서 기본 html radio를 스타일링 없이 사용하고 있는지 몰랐네요... 

reset css 도입을 결정할 때는 거의 모든 케이스에서 문제가 되지 않을거라고 판단했어요. 스토리북 케이스를 예시로 들자면 실제 베지어를 사용하는 곳에선 html radio 대신 RadioGroup, Radio 컴포넌트를 사용하게 될 거니까요.

좀 더 개선해보자면 [radix theme의 reset](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/reset.css)이나 [panda css의 reset](https://panda-css.com/docs/concepts/cascade-layers)처럼 옵셔널로 켜고 킬 수 있게 만들 수도 있을 거 같습니다. 아니면 reset css 범위를 베지어 컴포넌트에 영향이 안가는 정도로만 좁혀서 직접 작성하는 방법도 있을 거 같아요.

2024-01-04 05:48 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
베지어를 프론트에서 사용한다고 생각하면 스토리북처럼 고객사 사이트의 스타일링 오염이 있을것이라 생각했는데, 제가 잘못 생각한 걸까요? 저는 radix처럼 옵셔널하게 만드는 게 좋을 것 같네요.

2024-01-04 05:53 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
제가 이전에 확인해본바로는 고객사 스타일에 적용되는 부분은 베지어의 글로벌 스타일을 적용하지 않았어요. 이건 다시 프론트 팀이랑 더 자세히 확인해보고 확실하게 문제가 있다면 옵셔널하게 개선하는 게 좋아보입니다 👍 
(혹시 몰라 참고차 FYI @dinohan @heech1013)

2024-01-04 06:31 UTC, yangwooseong commented on packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
> +    all: unset;
reset layer와 별개로 아바타에서 unset이 불필요하기 때문에 지우겠습니다.

2024-01-04 07:40 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/useAvatarRadius.ts
> +export function useGetAvatarBorderRadius() {
- useAvatarRadiusToken 은 어떤가요?
- 함수명과 파일명이 같아야 할 거 같아요!

2024-01-04 07:40 UTC, sungik-choi commented on packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss
> +    color: var(--txt-black-dark);
마이너: 지금보니까.. Text의 color로 이동할 수 있을 거 같아요 😂

2024-01-04 13:47 UTC, sungik-choi approved these changes

2024-01-05 01:01 UTC, merged