Migrate `Tag`, `Badge` component with scss
channel-io/bezier-react pull request #1872
Opened 2024-01-03 03:01 UTC by yangwooseong

## Self Checklist

- [x] I wrote a PR title in **English** and added an appropriate **label** to the PR.
- [x] I wrote the commit message in **English** and to follow [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I [added the **changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) about the changes that needed to be released. (or didn't have to)
- [x] I wrote or updated **documentation** related to the changes. (or didn't have to)
- [x] I wrote or updated **tests** related to the changes. (or didn't have to)
- [x] I tested the changes in various browsers. (or didn't have to)
  - Windows: Chrome, Edge, (Optional) Firefox
  - macOS: Chrome, Edge, Safari, (Optional) Firefox

## Related Issue

- #1733 

## Summary

- `Tag`, `Badge`컴포넌트를 scss로 마이그레이션하고 `MarginProps`를 인터페이스에 추가합니다.

## Details

- 

### Breaking change? (Yes/No)

## References

2024-01-03 09:02 UTC, sungik-choi requested changes

2024-01-03 09:02 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const textColor: SemanticNames = givenColor || 'txt-black-darkest'
```suggestion
```

Tag의 Text 색상은 변하면 안됩니다. 기존에 없던 로직이에요.

2024-01-03 09:07 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const bgColor: SemanticNames = givenColor || getProperTagBadgeBgColor(variant)
Tag쪽 사용처 로직을 살펴보고, color prop은 제거하는 게 제일 좋을 거 같아요. 사용처에서 색상을 변경하는 방식이 variant, color 두 가지 방식으로 혼재되어있네요.. 생각보다 좀 복잡할 거 같아서 데스크에 별도 이슈 만들어서 진행해야할 수도 있겠어요

2024-01-04 03:22 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
> +  const textColor = getProperBadgeTextColor(variant)
네 맞아요. MonoChromeDark를 monochrome-dark로 변경한다던가했을 때, 데스크에서 대응이 필요할거에요

2024-01-04 04:24 UTC, yangwooseong commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const bgColor: SemanticNames = givenColor || getProperTagBadgeBgColor(variant)
이거는 scss 마이그레이션 하는 것과 별도로 진행하는게 좋을 것 같아요. 데스크에서 color를 사용하고 있어서 시간이 좀 걸릴 것 같습니다

2024-01-04 05:57 UTC, yangwooseong commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const textColor: SemanticNames = givenColor || 'txt-black-darkest'
`Tag`의 `color`속성 제거는 별도로 가져가려고 해서, `Badge`만 classname으로 변환하고 여기는 동적인 스타일로 유지해야 할 것 같습니다. 데스크에서 `color`속성의 사용처를 모두 `variant`로 옮기고 베지어에서 `TagBadgeBgColorPreset`, `BadgeColorPreset` 맵핑을 지워야 할 듯 합니다. 지금은 맵핑을 export하고 있네요..

2024-01-04 06:03 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const textColor: SemanticNames = givenColor || 'txt-black-darkest'
ㅋㅋㅋ그 땐 그랬습니다...

2024-01-04 07:31 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss
> +    --b-tag-badge-color: inherit;
없어도 괜찮지 않을까요?

2024-01-04 07:31 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +import { type SemanticNames } from '~/src/foundation'
마이너: `Tokens.ts` 의 `SemanticColor` 로 나중에 바뀌어야함.

2024-01-04 07:31 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
> +  const textColor: SemanticNames = givenColor || 'txt-black-darkest'
리마인드 드립니다!

2024-01-04 07:31 UTC, sungik-choi commented on packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss
> +    --b-tag-badge-background-color: inherit;
마이너: todo 주석 남겨놓으면 더 좋을 거 같습니다!

2024-01-04 13:45 UTC, sungik-choi approved these changes

2024-01-05 01:11 UTC, merged