Migrate `FormHelperText`, `FormErrorMessage`, and `FormLabel` component with scss
channel-io/bezier-react pull request #1893
Opened 2024-01-10 00:59 UTC by yangwooseong

## Self Checklist

- [x] I wrote a PR title in **English** and added an appropriate **label** to the PR.
- [x] I wrote the commit message in **English** and to follow [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I [added the **changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) about the changes that needed to be released. (or didn't have to)
- [x] I wrote or updated **documentation** related to the changes. (or didn't have to)
- [x] I wrote or updated **tests** related to the changes. (or didn't have to)
- [x] I tested the changes in various browsers. (or didn't have to)
  - Windows: Chrome, Edge, (Optional) Firefox
  - macOS: Chrome, Edge, Safari, (Optional) Firefox

## Related Issue

- #1733 

## Summary

- `FormHelperText`, `FormErrorMessage`, `FormLabel`컴포넌트를 scss로 마이그레이션 하고 `as`, `interpolation`속성을 인터페이스에서 제거합니다. 

## Details

- 각각의 컴포넌트를 scss로 마이그레이션할 때, `FormControl.styled.ts`에 있던 스타일 코드를 각 컴포넌트의 .module.scss로 이동시켰습니다. 또한 context로서 Wrapper컴포넌트를 주던 것을 labelPosition만 주고 각 컴포넌트의 .module.scss에서 스타일링 하도록 변경했습니다. 

### Breaking change? (Yes/No)

- Yes, `FormHelperText`, `FormErrorMessage`, `FormLabel` no longer supports `as` and `interpolation` props.

## References

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLParamElement

2024-01-11 06:45 UTC, sungik-choi requested changes
`FormControl` 에서 `FormLabel`, `FormHelperText` Wrapper를 가지고 있는 이유는 **`FormControl` 컨텍스트 아래에서만** 특정 레이아웃을 구현하기 위해서에요. 레이아웃의 책임을 `FormControl` 이 가지고 있기 때문에, Wrapper 컴포넌트를 `FormControl` 가까이에 위치시켰습니다.

`FormLabel`, `FormHelperText`가 Wrapper를 가지고 있지 않았기 때문에 스탠드얼론으로 사용할 수도 있었어요. Wrapper를 각 컴포넌트에서 가지고 있도록 변경되면, `FormControl` 의 레이아웃에 의존하는 padding, margin 속성들이 적용되어서 스탠드얼론으로 사용되는 케이스들의 레이아웃이 틀어지게 됩니다.

2024-01-11 06:48 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> + *
```suggestion
/**
 * `FormHelperText` is a component to show the description of the input element.
 *
```

단독으로도 사용할 수 있게 설계되었어요!

2024-01-11 06:51 UTC, sungik-choi commented
> 지금은 Text의 속성을 그대로 노출하고 있는데, 사실상 고정된 스타일(color, typo)를 사용하고 있기 때문에 이런 속성역시 제거해야되나 고민됩니다. 어떻게 생각하시는지 궁금합니다

사용처 확인해보고 오버라이드하는 곳이 거의 없다면 제거해도 좋을 거 같네요 👍

2024-01-11 07:44 UTC, yangwooseong commented
> `FormLabel`, `FormHelperText`가 Wrapper를 가지고 있지 않았기 때문에 스탠드얼론으로 사용할 수도 있었어요. Wrapper를 각 컴포넌트에서 가지고 있도록 변경되면, `FormControl` 의 레이아웃에 의존하는 padding, margin 속성들이 적용되어서 스탠드얼론으로 사용되는 케이스들의 레이아웃이 틀어지게 됩니다.

아하 그렇군요 제가 오해했네요. 그럼 이전 구현처럼 Control 에서 스타일링 된 Wrapper를 컨텍스트로 받도록 변경하겠습니다

2024-01-15 05:39 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
> +interface FormControlOptions {
OwnProps 로 변경되면 더 좋을 거 같아요!

2024-01-15 05:39 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
> className 을 주는게 더 간단해 보여서 컨텍스트로 Wrapper가 아닌 className을 내려주도록 했습니다. FormControl과 같이 쓰이지 않는 경우에는 이전 구현처럼 div로 감싸지 않은 상태로 렌더링되도록 했습니다. 사실 굳이 하나 더 div element 를 주지 않고 className만 합치면 될 것 같은데, 고민하다가 이 부분은 이전과 동일하게 별도의 div element를 주는 방식으로 했습니다.

말씀주신대로 className만 내려주는 게 더 깔끔하겠네요..! FormLabel의 style, className, ref로 Wrapper가 가지는 스타일을 오버라이드가 가능하도록 변경되긴 하지만 크게 문제될 부분은 없어보입니다

2024-01-15 05:39 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
마이너: `classNameFromControl` -> `className` 은 어떤가요? 개인적인 선호인데, 반환값은 일반적인 네이밍으로 하고 사용처에서 필요한 경우 변수명을 변경하는 게 FormControl에서 컨텍스트를 통해 내려주는 다른 속성들(id, ref...)의 네이밍을 생각해봤을 때 더 일관성이 있는 거 같아요.

`{ className: classNameFromControl }`

2024-01-15 06:08 UTC, yangwooseong commented on packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
> +interface FormControlOptions {
FormControl 은 별도pr 에서 작업하겠습니다!

2024-01-15 06:13 UTC, yangwooseong commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
> 말씀주신대로 className만 내려주는 게 더 깔끔하겠네요..! 

맥락이 약간 헷갈리네요. (컨텍스트에 있는 className을 의미하는 게 아니라) 제가 제안한 것처럼 div element 를 제거하고 className만 추가하는 방식으로 바꾸는 게 좋겠다는 말씀이신가요?

2024-01-15 06:16 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
네 맞아요. "사실 굳이 하나 더 div element 를 주지 않고 className만 합치면 될 것 같은데" <- 이 부분입니다

2024-01-15 06:16 UTC, sungik-choi commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
두번째 코멘트는 그것과 별개로 변수명에 대한 코멘트에요

2024-01-15 06:16 UTC, yangwooseong commented on packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
> +    classNameFromControl,
이해했습니다 감사합니다!

2024-01-15 10:11 UTC, sungik-choi approved these changes

2024-01-16 02:56 UTC, merged