web-desk만을 위한 toastContainer의 위치용 상수 제거
channel-io/bezier-react pull request #1915
Opened 2024-01-15 01:18 UTC by leejiwoo2002

## Self Checklist

- [ ] I wrote a PR title in **English** and added an appropriate **label** to the PR.
- [ ] I wrote the commit message in **English** and to follow [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I [added the **changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) about the changes that needed to be released. (or didn't have to)
- [ ] I wrote or updated **documentation** related to the changes. (or didn't have to)
- [ ] I wrote or updated **tests** related to the changes. (or didn't have to)
- [ ] I tested the changes in various browsers. (or didn't have to)
  - Windows: Chrome, Edge, (Optional) Firefox
  - macOS: Chrome, Edge, Safari, (Optional) Firefox

## Summary

web-desk의 GNB 만큼의 좌측 여백을 확보하던 스타일링을 제거합니다

## Details

이제 toast의 표시 위치가 toastContainer의 좌/우 하단에 위치하게 됩니다

### Breaking change? (Yes/No)

Yes
만약 좌하단의 여백을 기존 동작처럼 유지하고 싶다면
1. document.body 하위에 container를 위치하고
2. container의 position을 원하는 만큼 변경해야 합니다 (as-is left:68px)

2024-01-15 01:45 UTC, Tanney-102 approved these changes

2024-01-15 04:40 UTC, sungik-choi requested changes

2024-01-15 04:40 UTC, sungik-choi commented on .changeset/quiet-days-grow.md
> +Remove toastcontainer location constants for specific applications
Breaking change이므로 major 버전 업데이트가 되어야하지만, 현재 prerelease를 사용할 수는 없어서, 하위 호환성을 보장해주는 방식으로 변경하면 좋겠습니다.

기존에 Toast를 사용하던 유저들에겐 버전을 업데이트하더라도 아무런 영향이 없도록 새로운 속성을 추가하는 방향이 되어야할 거 같아요.

See: https://github.com/channel-io/bezier-react/wiki/Contribute#%EC%9C%A0%EC%9D%98%EC%A0%81-%EB%B2%84%EC%A0%84-%EB%AA%85%EC%84%B8semver

2024-01-15 04:41 UTC, sungik-choi commented
추가) 셀프 체크리스트 검토 부탁드립니다!

2024-01-15 06:09 UTC, leejiwoo2002 commented
@sungik-choi 혹시 PR 제목/내용을 영어로 쓰도록 강제하는 룰을 지켜야 할까용

2024-01-15 06:20 UTC, sungik-choi commented
> @sungik-choi 혹시 PR 제목/내용을 영어로 쓰도록 강제하는 룰을 지켜야 할까용

내용은 한글로 해도 무방하고, 제목만 영어로 적어주시면 좋을 거 같아요. (I wrote a PR **title** in English)

2024-01-15 06:23 UTC, leejiwoo2002 commented on .changeset/quiet-days-grow.md
> +Remove toastcontainer location constants for specific applications
옙 props를 하나 더 두는 방향으로 살펴보겠습니다

2024-01-15 07:00 UTC, leejiwoo2002 commented
@sungik-choi 결국 toastProvider와 toastContainer에 props를 하나 추가하고, getPlacement 함수에 주입하여
기존처럼 or 바뀐것 을 분기하는게 좋을것 같은데 어떠실까요?

2024-01-15 07:02 UTC, sungik-choi commented
> @sungik-choi 결국 toastProvider와 toastContainer에 props를 하나 추가하고, getPlacement 함수에 주입하여 기존처럼 or 바뀐것 을 분기하는게 좋을것 같은데 어떠실까요?

좋은 거 같습니다!

2024-01-15 10:48 UTC, sungik-choi reviewed
저는 불린 플래그 하나로 `GNB_WIDTH` 만큼의 left 오프셋을 줄지 말지를 컨트롤하는 것보다, `offset` 같은 객체를 전달해서 right, left, bottom 오프셋에 적용되도록 하면 좋을 거 같다고 생각했어요. 

현재 변경 사항이 적용된 이후 `GNB_WIDTH` 를 Toast에서 제거하는 Breaking change가 있다면(Toast를 전부 뜯어 고치지 않는다고 가정), 이 때 `GNB_WIDTH` 가 필요한 데스크 사용처를 위해 외부에서 오프셋을 주입해줄 수 있도록 하는 추가적인 작업이 필요합니다.

오프셋 객체를 전달하되, 오프셋 객체의 기본값에 `GNB_WIDTH` 를 포함하는 방식으로 변경한다면 이후 Breaking change를 발생시킬 때 베지어 / 사용처의 대응 작업이 간편해집니다(오프셋 기본값이 `{ right: 0, bottom: 0, left: 0 }` 으로 변경된다면, 기존 데스크 사용처에서는 `{ left: 68 }` 만 다시 추가해주도록 변경하면 되니까요).

```tsx
type Offset = { right?: number, bottom?: number, left?: number }

const ToastContainer = ({
  placement,
  offset = {
    right: 0,
    bottom: 0,
    left: 68 // GNB_WIDTH
  }, // ToastProvider에서 기본값 선언
  ...props
}: ToastContainerProps) => (
  <Container
    placement={placement}
    offset={offset}
    {...props}
  />
)

function getPlacement(placement: ToastPlacement, offset: Offset) { /* ... */ }
```

2024-01-15 23:10 UTC, leejiwoo2002 commented
@sungik-choi 음 좌/우/하단 props를 열어두길 기대하셨었군요, 이건 저랑 의견이 잘 맞지 않았나 봅니다
제안주신건 좋아보여서 반영해보겠습니다

2024-01-16 04:24 UTC, yangwooseong approved these changes

2024-01-16 05:56 UTC, sungik-choi approved these changes

2024-01-16 05:56 UTC, sungik-choi commented on .changeset/quiet-days-grow.md
> +Remove toastcontainer location constants for specific applications
변경 사항에 대해 체인지로그만 더 자세히 업데이트해주시면 💯 
- 추가된 속성
- 사용방식

2024-01-16 06:02 UTC, leejiwoo2002 commented on .changeset/quiet-days-grow.md
> +Remove toastcontainer location constants for specific applications
props 내용 추가해야겠네요 감사합니다

2024-01-16 06:36 UTC, sungik-choi commented
머지 해주셔도 됩니다! 코드 커버리지는 옵셔널 체크라서 무시하셔도 돼요

2024-01-16 06:42 UTC, merged