TextArea의 rows설정을 TextAreaSize를 통해서 하도록 변경
channel-io/bezier-react pull request #584
Opened 2021-09-15 10:57 UTC by Jay-WKJun

# Description

TextArea의 rows설정을 기존에 숫자를 prop으로 넣어 변경해 주던 것을 TextAreaSize를 통해서 하도록 변경하였습니다.

## Changes Detail
* TextArea.tsx의 maxRows, minRows prop을 삭제, 대신 size prop을 받도록 변경
* size prop은 TextAreaSize enum만을 받아들이도록 제한
* size prop은 mapping되어 maxRow로 설정됨
* minRow는 5로 고정됨

# Tests
- [x] Jest 테스트 코드 작성 완료
- [x] Storybook 작성 완료

## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [x] Chrome - Blink
- [x] Edge - Blink
- [x] Firefox - Gecko (Option)
### macOS
- [x] Chrome - Blink
- [x] Edge - Blink
- [x] Safari - WebKit
- [x] Firefox - Gecko (Option)

# (Option) Issues
(연관된 PR이나 Task / 특정 시점까지 머지하면 안됨 / 번역 추가 필요 / ...)
* 이슈 없음.

2021-09-15 11:12 UTC, inhibitor1217 requested changes

2021-09-15 11:12 UTC, inhibitor1217 commented on src/components/Input/TextArea/TextArea.types.ts
> +
이것도 `TextArea/index.ts`에서 export해주어야 사용처에서 import하여 사용할 수 있습니다.

2021-09-15 11:48 UTC, sungik-choi commented on src/components/Input/TextArea/TextArea.tsx
> +        minRows={5}
`5` 상수 분리하는 편이 좋아보이네요

2021-09-15 12:22 UTC, sungik-choi commented
> 변경사항 개요를 작성해주세요. Github 이슈, Notion 등 연관 문서가 있다면 첨부해주세요.

PR 설명에서 이 라인 삭제해주시고 연관 문서 첨부해주시거나 변경 이유를 설명해주시면 더욱 좋을 거 같습니다.

2021-09-16 08:32 UTC, inhibitor1217 approved these changes

2021-09-16 08:37 UTC, sungik-choi approved these changes

2021-09-16 09:42 UTC, psi9730 approved these changes

2021-09-16 11:02 UTC, merged

2021-09-16 11:06 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.37 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.37)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.37)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: