enhance: 절대경로 및 import order 적용
channel-io/bezier-react pull request #650
Opened 2021-12-03 10:57 UTC by sungik-choi

# Summary

프로젝트에 절대경로를 적용하고, `import/order` 룰을 적용합니다.

> ⚠️ https://github.com/channel-io/bezier-react/pull/650/commits/eafd39b62989161069d34e904362f36ad5ba417d 커밋 diff가 커서, 해당 커밋 제외하고 커밋별로 보시면 편합니다.

# Details

## Config

- [`@rollup/plugin-alias`](https://www.npmjs.com/package/@rollup/plugin-alias) 패키지 설치: rollup이 path alias를 해석할 수 있도록 하는 플러그인
- [`tsconfig-paths-webpack-plugin`](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin) 패키지 설치: tsconfig의 path alias를 storybook에 그대로 가져오기 위한 플러그인
- `rollup.config` 에 alias path 추가
- `tsconfig` 에 alias path 추가
- `jest.config` 에 alias path 추가
- `eslintrc` 에 `import/order` 룰을 적용, 불필요한 rule 삭제
  - 채널 데스크에서 사용한는 방식과 흡사하게 적용했으며, `foundation` 의 우선권이 가장 높도록 설정

## Storybook Type Enhance

```json
/* tsconfig.json */
  "exclude": [
    "node_modules",
    "build",
    -- "src/**/*.stories.tsx",
  ]
```

- 스토리북 테스트코드에도 절대경로가 적용될 수 있도록 하기 위해, 기존 `tsconfig` 의 exclude 리스트에서 스토리북 확장자를 제거했습니다.
- 제거하면서 타입 지정 미비한 부분들에서 모두 컴파일 에러가 나서, 올바른 타입을 지정해주었습니다.
- Story Template args 사용 방식 통일(ing, 불필요한 spread 제거)
- Story 파일의 잘못된 CSS Property 순서 수정
- 잘못된 Story Meta argTypes 수정

## etc

 - import 컨벤션이 single line, multi line 두 가지 방식이 혼재되어 있어, 절대 경로를 적용하면서 'max-len 린트 에러가 나지 않는 선에서' singlie line으로 일괄 변경
- `downlevelIteration` 관련해서 발생하는 에러 수정
  - `Array.from` 사용하는 방식으로 수정했는데, 다른 방식도 있을 듯
  - cf. [blog](https://mariusschulz.com/blog/downlevel-iteration-for-es3-es5-in-typescript), [stackoverflow](https://stackoverflow.com/questions/53441292/why-downleveliteration-is-not-on-by-default)

2021-12-06 10:39 UTC, sungik-choi commented
로컬에선 에러가 없는데 CI에서 module resolve 에러나서 해결중입니다...

2021-12-07 02:28 UTC, dinohan approved these changes
고생... 하셨습니다..!!

2021-12-07 05:23 UTC, inhibitor1217 approved these changes

2021-12-07 09:10 UTC, sungik-choi commented
빌드 시 타입 선언 파일만 만들어지는 버그가 있어 확인중입니다... (with @quino0627)

2021-12-07 11:13 UTC, quino0627 requested changes

2021-12-07 11:13 UTC, quino0627 commented on rollup.config.js
> +
현재 방식대로라면 rollup 이 올바르게 번들링을 수행하지 못하고 비어있는 package를 생성하게 됩니다. build 했을 때 파일을 확인해주세요~
다음과 같이 바꾸면 문제 없이 잘 됩니다.
```suggestion
const aliasPlugin = alias({
  entries: {
    Components: path.resolve(projectRootDir, 'src', 'components'),
    Constants: path.resolve(projectRootDir, 'src', 'constants'),
    Foundation: path.resolve(projectRootDir, 'src', 'foundation'),
    Hooks: path.resolve(projectRootDir, 'src', 'hooks'),
    Layout: path.resolve(projectRootDir, 'src', 'layout'),
    Types: path.resolve(projectRootDir, 'src', 'types'),
    Utils: path.resolve(projectRootDir, 'src', 'utils'),
    Worklets: path.resolve(projectRootDir, 'src', 'worklets'),
  },
})
```

2021-12-07 11:14 UTC, quino0627 commented on rollup.config.js
> +
path.resolve는 따로 빼는게 깔끔하겠죵?

2021-12-07 11:16 UTC, quino0627 commented on rollup.config.js
> +
![image](https://user-images.githubusercontent.com/33861398/145019587-2837f472-e5d7-4884-83d3-907da7f0b7c3.png)
![image](https://user-images.githubusercontent.com/33861398/145019616-9a2a7e97-cccd-440b-b4e3-27ad39f491ef.png)

실제로 aliasing이 잘 적용된 모습

2021-12-07 11:18 UTC, quino0627 commented on rollup.config.js
> +
```typescript
import path from 'path'
const projectRootDir = path.resolve(__dirname)
```

2021-12-07 11:22 UTC, quino0627 reviewed
> import 컨벤션이 single line, multi line 두 가지 방식이 혼재되어 있어, 절대 경로를 적용하면서 'max-len 린트 에러가 나지 않는 선에서' singlie line으로 일괄 변경

요건 좀 회의적인데요, 두개 이상 import 해올시에는 항상 multi가 좋을 것 같다는 의견입니다
(multiline은 수정, 추가가 용이하기 때문)

2021-12-07 11:56 UTC, sungik-choi commented
> > import 컨벤션이 single line, multi line 두 가지 방식이 혼재되어 있어, 절대 경로를 적용하면서 'max-len 린트 에러가 나지 않는 선에서' singlie line으로 일괄 변경
> 
> 요건 좀 회의적인데요, 두개 이상 import 해올시에는 항상 multi가 좋을 것 같다는 의견입니다 (multiline은 수정, 추가가 용이하기 때문)

작업하다보니 single line 비중이 훨씬 커서 이 방식으로 통일한거긴해요. 작업자 성향에 따라 아무거나 골라서 사용해도 큰 상관은 없을 거 같은데, 나중에는 하나로 통일되면 좋을 거 같습니다.

2021-12-08 02:40 UTC, quino0627 approved these changes
👍

2021-12-08 02:41 UTC, merged

2021-12-08 02:45 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.62 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.62)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.62)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: