EmojiAvatar component 추가
channel-io/bezier-react pull request #683
Opened 2022-01-03 10:21 UTC by CHEWCHEWW

# Summary

- Desk의 TeamChatIcon 컴포넌트를 기반으로 EmojiAvatar 컴포넌트를 제작했습니다.

# Details

[논의](https://github.com/channel-io/bezier-react/pull/675#discussion_r772335993)
[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=0%3A1)

현재 Desk의 TeamChatIcon은 emoji, emojiName을 받아 내부적으로 Fallback 처리를 해주고 있습니다.
하지만 해당 컴포넌트의 경우 emojiUrl을 받아 보여주는 역할만 수행하고, 나머지 행동은 사용처에서 외부적으로 처리해주도록
구현되었습니다. (오프라인 논의)

또한 현재는 TeamChatIcon에서는 1가지 사이즈로 운용되고 있지만,
피그마에 맞추어 다양한 사이즈를 받을 수 있도록 구현했습니다.

(TeamChatIcon과 사이즈 다른데 어떻게 사용할지 체크해야함)
- 
## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)
### macOS
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Safari - WebKit
- [ ] Firefox - Gecko (Option)

# References

2022-01-05 06:09 UTC, inhibitor1217 requested changes

2022-01-05 06:09 UTC, inhibitor1217 commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
AvatarSize와 EmojiAvatarSize를 따로 만들어야 할까라는 의문이 살짝 스쳤습니다 :) 의견이 궁금합니다

2022-01-05 06:09 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +  const handleClickIcon = useCallback((event) => {
```suggestion
  const handleClickIcon = useCallback((event: ???) => {
```

2022-01-05 06:09 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +
```
cursor: pointer;

${({ unClickable }) => unClickable && css`
  cursor: initial;
`}
```

2022-01-05 06:09 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +  height: ${WRAPPER_SIZE}px;
호버되는 영역이 24px로 고정되어있으면 안됩니다. Avatar Size에 따라 달라져야 합니다.

https://user-images.githubusercontent.com/25701854/148168831-94a89c1e-7925-4743-b76f-3866ba8b9930.mov

2022-01-17 04:06 UTC, quino0627 commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
저도 에이프릴의 의견이 궁금합니다

2022-01-17 04:45 UTC, quino0627 commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +interface WraaperProps {
```suggestion
interface WrapperProps {
```

2022-01-17 04:45 UTC, quino0627 commented on src/foundation/Mixins.ts
> +  background-position: center;
다른이야기지만, Mixins.ts의 absoluteCenter가 받는 otherTransforms 의 타입은 다음과 같이 규정할 수 있지 않을까요?

```
export const absoluteCenter = (otherTransforms?: SimpleInterpolation) => `
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) ${otherTransforms};
`
```
![image](https://user-images.githubusercontent.com/33861398/149709363-cad53b66-4ca3-4848-9767-0984a3b04a5b.png)

2022-01-17 06:45 UTC, quino0627 commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +      >
제 생각에는 적절한 role이 설정되어야 할 것 같습니다.
presentation 혹은 img 일 것 같은데, 개인적으로는 img가 더 적절해 보입니다.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#using_roleimg_to_confer_meaning_that_is_obscured_or_implied

2022-01-17 07:29 UTC, rktguswjd commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
저도 궁금합니다! (아바타 사이즈에 없는 이모지 아바타 사이즈는 16, 아바타 사이즈에서 이모지 아바타 사이즈로 사용하지 않는 사이즈는 48뿐)

2022-01-17 07:37 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
많은 분들에게 의문을 가질 스펙을 만들어서 마음이 아프군요..

일단은 피그마 스펙 상 기존 아바타 사이즈에 없는 16, 48 사이즈가 존재하고,
현재는 팀챗의 아이콘 컴포넌트에서만 사용하고 있지만, 스펙 상 앞으로는 사용처가 늘어날 수도 있다 생각하고 작업했습니다.
아바타 컴포넌트와는 역할이 다르고, 구분되어야 하는 컴포넌트라고 생각하기도 했습니다.

결론적으로 아바타 컴포넌트와 연관성을 가질 필요가 없다는 판단으로 만든 사이즈입니다만
이정도의 이유라면 기존 AvatarSize를 이용하는 것이 적절할까요?
(사실 이 논의와 약간은 관련이 있었던 판단에 대해 이어가자면, avatar folder 그룹 내에 emojiAvatar 컴포넌트를 위치하고 하위 컴포넌트로 두는 것이 적절할지에 대한 판단도 다시 해보아야 한다고 생각합니다)

2022-01-17 10:15 UTC, inhibitor1217 commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
> 아바타 컴포넌트와는 역할이 다르고, 구분되어야 하는 컴포넌트라고 생각하기도 했습니다.

👌

2022-01-18 10:13 UTC, quino0627 commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
의문을 가졌던 것은 아니고 에이프릴의 의견이 궁금했던 것이었습니다 :)

2022-01-21 08:31 UTC, rktguswjd commented on src/components/EmojiAvatar/index.ts
> +import EmojiAvatarProps, { EmojiAvatarSize } from './EmojiAvatar.types'
굿굿

2022-01-24 12:08 UTC, sungik-choi commented
요거 마무리 부탁드립니다~!

2022-01-25 12:01 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +  height: ${WRAPPER_SIZE}px;
요거 다시 사이즈 체크하겠습니다.

2022-01-26 09:48 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +export default EmojiAvatar
오프라인 싱크) 컴포넌트를 사용하는 곳에서 memoization 처리하도록 구현(avatar component도 동일한 기조)

2022-01-26 16:54 UTC, quino0627 approved these changes

2022-01-27 04:23 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +
unclickable일 때, hover style도 적용 안되도록 가능할까요?

2022-01-27 04:23 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +}: EmojiAvatarProps) {
`as`, `style` prop 지원 부탁드려요!

2022-02-03 03:19 UTC, sungik-choi commented on src/foundation/Mixins.ts
> +`
```suggestion
export const centeredBackgroundImage = <Type extends number | string>(imageUrl: string, ...sizes: [Type] | [Type, Type]): ReturnType<typeof css> => {
  const [width, height = width] = sizes
  return css`
    background-image: url(${imageUrl});
    background-position: center;
    background-repeat: no-repeat;
    background-size: ${width}px, ${height}px;
    background-clip: content-box;
  `
}
```

반드시 필요한 매개변수는 필수로 하는 게 좋을 거 같아요. 옵셔널로 두게 되면 잘못된 css 속성을 반환하게 됩니다.

2022-02-03 03:19 UTC, sungik-choi commented on src/foundation/Mixins.ts
> +export const absoluteCenter = (otherTransforms: SimpleInterpolation) => `
1. 이 함수도 단순 string 대신 `css` 를 반환하도록 하는 게 이 모듈 전체적인 일관성에 있어서 좋아보입니다
2. 매개변수 타입을 옵셔널로 해도 될 거 같아요

2022-02-03 03:19 UTC, sungik-choi commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +        unClickable={!clickable || !onClick}
`onClick` 이 비어있는지 아닌지로 클릭 가능 여부를 판별할 수 있지 않을까요? `clickable` 변수를 별도로 두지 않아도 충분할 거 같다는 생각입니다.

2022-02-03 03:19 UTC, sungik-choi commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +        style={{ backgroundImage: `url('${emojiUrl}')` }}
이 스타일만 별도로 `style` 속성을 통해 주입해주신 이유를 알 수 있을까요?

2022-02-03 03:19 UTC, sungik-choi commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +  }
border radius, hover 스타일이 디자인 시스템에는 정확히 명시되어있지 않아서, 제이미와 함께 이야기해보면 좋겠습니다.

2022-02-03 03:19 UTC, sungik-choi commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +export const Wrapper = styled.div`
```suggestion
export const Wrapper = styled.button`
```

이 컴포넌트가 클릭 가능한 컴포넌트라면 `Wrapper` 컴포넌트는 `button` 엘리먼트가 되는게 맞을 거 같아요. 클릭 가능 여부에 따라 `as` 속성을 통해 `div` <-> `button` 전환이 되었으면 좋겠습니다.

2022-02-03 04:03 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +  }
넵 요부분 다시 체크할게요

2022-02-03 07:26 UTC, sungik-choi approved these changes
👍

2022-02-03 07:28 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/EmojiAvatar.styled.ts
> +  }
요거 border 스타일 avatar와 동일하게 가는걸로 들었습니다! 변경하겠습니다

2022-02-07 01:39 UTC, inhibitor1217 requested changes

2022-02-07 01:39 UTC, inhibitor1217 commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +      as={as || !isNil(onClick) ? 'button' : 'div'}
operator precedence에 따라서 `||`가 먼저 evaluate됩니다.
```suggestion
      as={as || (!isNil(onClick) ? 'button' : 'div')}
```

2022-02-09 21:57 UTC, CHEWCHEWW commented on src/components/EmojiAvatar/EmojiAvatar.tsx
> +      as={as || !isNil(onClick) ? 'button' : 'div'}
요거 이제 관련 사항은 필요 없어졌지만.. 이런 부분들이 테스트가 미리 작성되어있었다면 놓치지 않았겠다는 아쉬움이 드네요.

2022-02-10 04:33 UTC, inhibitor1217 commented on src/components/Emoji/Emoji.test.tsx
> +  it('should render emoji icon with size prop - size20', () => {
```suggestion
  it('should render emoji icon with size prop - size16', () => {
```

2022-02-10 04:33 UTC, inhibitor1217 commented on src/foundation/Mixins.ts
> +    background-image: url(${imageUrl});
많은 이모지를 한번에 렌더링하는 경우, imageUrl이 모두 서로 다르기 때문에 각 emoji마다 classname이 생성됩니다. 이로 인해 동적으로 스타일시트에 많은 classname이 추가되어 성능 이슈가 있습니다. (비슷한 문제가 Avatar에서 발생했었습니다. #561 참고)

#561 의 해결 방식처럼, imageUrl은 css variable로 다루는 것이 좋아 보입니다.

2022-02-10 04:35 UTC, inhibitor1217 commented on src/components/Emoji/Emoji.tsx
> +}: EmojiProps) {
ref forwarding 해주세요.

2022-02-11 07:40 UTC, quino0627 commented on src/foundation/Mixins.ts
> +`
타입 깎는 에드

2022-02-11 07:57 UTC, quino0627 reviewed
`Icon`이 `role="img"` 를 가지고 `aria-label={name}` 을 받을 수 있게 하면 접근성 측면에서 좋을 것 같아요

2022-02-11 07:57 UTC, quino0627 commented on src/components/Emoji/index.ts
> +import EmojiProps, { EmojiSize } from './Emoji.types'
```suggestion
import { EmojiSize } from './Emoji.types'
import type EmojiProps from './Emoji.types'
```
`import type`구문을 사용하게 되면 컴파일 시에 타입 선언을 더 잘 지워줍니다~

2022-02-11 07:57 UTC, quino0627 approved these changes
이외에는 좋습니다~

2022-02-21 01:31 UTC, inhibitor1217 approved these changes

2022-02-23 03:13 UTC, quino0627 reviewed
Conflict resolve 이후에 머지 부탁드립니다 ~

2022-02-23 03:45 UTC, merged

2022-02-23 03:54 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.98 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.98)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.98)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: