Button 의 최신 디자인 스펙 반영
channel-io/bezier-react pull request #701
Opened 2022-01-25 09:49 UTC by npbg

# Summary

[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=39%3A2) 에 있는 스펙에 맞게 Button 의 padding 값 결정 로직을 업데이트했습니다.

# Details

기존의 Button 의 padding 값 결정 로직은 text prop 의 유무로 결정되었습니다.

```typescript
case ButtonSize.L:
  return css`
    min-width: 44px;
    height: 44px;
    padding: 12px ${isEmpty(text) ? 12 : 10}px;
  `
```

새로운 디자인 스펙 상 버튼의 padding 은 다음과 같은 케이스마다 다릅니다.

1. 버튼에 text 가 없는 경우
2. styleVariant 가 Floating 인 경우
3. padding이 들어갈 곳 바로 옆에 텍스트가 있는 경우
4. padding이 들어갈 곳 바로 옆에 컨텐츠(ex. 아이콘)가 있는 경우

이에 따라 로직을 분리했습니다.

## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)
### macOS
- [x] Chrome - Blink
- [ ] Edge - Blink
- [ ] Safari - WebKit
- [ ] Firefox - Gecko (Option)

# References

[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=39%3A2)

2022-01-25 10:45 UTC, Seolhun commented on src/components/Button/Button.styled.ts
> +    floating: (BUTTON_SIZE_VALUE[ButtonSize.XL] / 2) - TEXT_MARGIN_VALUE[ButtonSize.XL],
MagicNumber가 많아서 이해하기가 힘든것 같습니다.
어떤 것을 같이 봐야 이해하기 편할까요?

2022-01-25 10:54 UTC, npbg commented on src/components/Button/Button.styled.ts
> +    floating: (BUTTON_SIZE_VALUE[ButtonSize.XL] / 2) - TEXT_MARGIN_VALUE[ButtonSize.XL],
아 이렇게보니 리뷰하시기 힘드시겠네요. 내일 주석으로 로직을 달아놓겠습니다. 우선은 리뷰 펜딩 부탁드립니다.

2022-01-26 04:24 UTC, inhibitor1217 commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
Button.tsx 보시면 hasContent를 `!!leftContent`, `!!rightContent`로 결정하는데 여기에 적어주신 1/2번 분기와 조건이 달라서 어떤 것이 실제 의도인지 잘 모르겠네요!

2022-01-26 04:40 UTC, npbg commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
아 이해했습니다. text prop 이 있어서 leftContent 와 rightContent 엔 text 와 같은 것은 오지 않는다는 전제를 한 것 같은데, sideContent 타입이 React.ReactNode 라 <Text /> 와 같은 컴포넌트로 오면 이를 어떻게 처리해야할지 고민되네요...

2022-01-28 01:23 UTC, npbg commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
일단은 디자인팀에 저 sideContent 부분에 텍스트가 또 들어갈 수 있는지 확인해봐야겠네요. 그렇지 않다면 
> leftContent 와 rightContent 엔 text 와 같은 것은 오지 않는다는 전제

를 깔고 가도 괜찮을 것 같아서요.

2022-02-03 06:16 UTC, sungik-choi reviewed
저는 피그마에서 관리하는 것과 동일하게, 아이콘만 들어가는 케이스를 별도로 관리하면 좋겠다는 생각이 들어요. 현재 아이콘이 있는 버튼을 사용하려면 보통 아래와 같이 사용하는데, 직관적않다고 생각합니다. 아이콘이 `leftContent` 에도, `rightContent` 에도 들어갈 수 있는게 조금 이상하게 느껴집니다. 무엇보다도, `text` 의 유무를 따져서 padding 값을 결정하는 로직이 너무 복잡한 거 같아요.

```tsx
<Button leftContent="foo" />
```

이렇게 되면 깔끔할 거 같아요.

```tsx
/* iconOnly 속성을 주면 iconName prop을 주입해줄 수 있습니다. 내부적으론 속성 여부에 따라 padding이 변경됩니다 */
<Button iconOnly iconName="foo" />
```

제안) 아래처럼 커스텀 타입 가드와 함께 구현할 수 있을 거 같습니다.

```tsx
/* types */
interface BaseButtonOptions {
  type?: HTMLButtonElement['type']
  loading?: boolean
  active?: boolean
  styleVariant?: ButtonStyleVariant
  colorVariant?: ButtonColorVariant
  onClick?: MouseEventHandler
  onMouseEnter?: MouseEventHandler
  onMouseLeave?: MouseEventHandler
  onBlur?: MouseEventHandler
}

export interface TextButtonOptions extends
  BaseButtonOptions,
  SideContentProps<SideContent, SideContent> {
  iconOnly?: false
  text?: string
}

export interface IconButtonOptions extends BaseButtonOptions {
  iconOnly: true
  iconName: IconName
}

interface BaseButtonProps extends
  BezierComponentProps,
  DisableProps,
  SizeProps<ButtonSize> {}

export interface TextButtonProps extends
  BaseButtonProps,
  TextButtonOptions {}

export interface IconButtonProps extends
  BaseButtonProps,
  IconButtonOptions {}

/* tsx */
type ButtonProps = TextButtonProps | IconButtonProps
function isTextButton(props: ButtonProps): props is TextButtonProps { return !props.iconOnly }
function isIconButton(props: ButtonProps): props is IconButtonProps { return props.iconOnly }
function Button(props: ButtonProps) { ... }
```

2022-02-03 06:16 UTC, sungik-choi commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
시안을 보면 버튼 자체의 padding은 사이드에 텍스트가 있으나, 아이콘이 있으나 (1, 2번 케이스) 항상 똑같은 거 같아요.
플로팅 버튼이 padding이 약간 다른 특이케이스고(3번 케이스), 아이콘만 있는 경우(4번 케이스)가 전체적으로 조금씩 다릅니다. 

<img width="335" alt="스크린샷 2022-02-03 오후 3 00 58" src="https://user-images.githubusercontent.com/58209009/152289630-62a46102-9d8d-411b-a45c-661270014e1a.png">

그리고 4번 케이스는 피그마에서 `icon-only` 베리언츠로 관리하고 있어요. 이 속성 여부에 따라 버튼의 padding이 변경됩니다.
1, 2번이 다른 케이스를 제가 찾지 못한 거일 수도 있어서, 확인 한 번만 부탁드려요

2022-02-03 06:17 UTC, npbg commented on src/components/Button/Button.styled.ts
> +  }
Icon only 의 경우 padding 필요없이 가운데 정렬만 되면 되기 때문입니다.

2022-02-03 06:22 UTC, npbg commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
SideContent 에는 Text 아닌 Icon, Avatar, Image 와 같은 것이 올 수도 있다고 하셨습니다. SideContent 의 type 을 IconName 으로 할 순 없을 것 같은데, Text 컴포넌트 와 같은 것은 오지 않는다는 전제를 해도 될 것 같긴 합니다.

2022-02-03 06:26 UTC, sungik-choi commented on src/components/Button/Button.styled.ts
> +  }
아 기존의 스타일링 방식이 height 가 픽스되어 있는 방식이라 그렇군요

2022-02-08 13:24 UTC, quino0627 reviewed
에드 리뷰 반영 후 리뷰하겠습니다
IconButton 의 분리 저는 좋아 보이는데, 제이미랑 한번 이야기해봐주시는 것도 좋을 것 같아요

2022-02-24 05:21 UTC, npbg commented on src/components/Button/Button.styled.ts
> +}
Text 의 padding 으로 처리하는게 더 낫겠네요!

2022-02-24 05:22 UTC, npbg commented on src/components/Button/Button.styled.ts
> +}
상하의 경우엔 어차피 버튼 height 정해져있고 중앙정렬이라 큰 상관 없을 것 같아요

2022-02-24 13:12 UTC, npbg commented on src/components/Button/Button.styled.ts
> +// 2. 해당 사이드에 텍스트가 아닌 컨텐트가 있을 경우 (ex. 아이콘) - contentSide
이건 디자인팀이랑 상의 후 추후 PR로 작업해 볼 것 같아요

2022-02-28 05:34 UTC, sungik-choi approved these changes

2022-03-02 01:37 UTC, inhibitor1217 requested changes

2022-03-02 01:37 UTC, inhibitor1217 commented on src/utils/styleUtils.ts
> +}
`next-v1` 최신에서 보시면 `FormGroup.styled.ts`에 동일한 유틸이 있습니다.
그곳의 유틸을 이것으로 대체해주세요.

2022-03-02 01:37 UTC, inhibitor1217 commented on src/components/Button/Button.tsx
> +      case ButtonSize.L:
이 변경은 맞나요? Figma에는 L사이즈 typography가 Size15인 것 같아요.

2022-03-02 01:37 UTC, inhibitor1217 commented on src/components/Button/Button.tsx
> +      case ButtonSize.XL:
동일, XL사이즈 아이콘 크기는 Normal로 되어있습니다.

2022-03-02 01:42 UTC, inhibitor1217 commented
사이즈별로 border-radius도 바뀌었는데, 체크 부탁드립니다.

2022-03-02 01:46 UTC, inhibitor1217 commented
L, XL사이즈일 때 버튼 전체 좌우 padding이 맞지 않습니다.

### L

![스크린샷 2022-03-02 오전 10 44 20](https://user-images.githubusercontent.com/25701854/156278908-3ff946c5-9c85-4c01-8730-29d85578984b.png)
<img width="280" alt="스크린샷 2022-03-02 오전 10 44 14" src="https://user-images.githubusercontent.com/25701854/156278839-08c4cb03-bde9-499a-aff4-c6692701e7f9.png">


### XL

![스크린샷 2022-03-02 오전 10 44 27](https://user-images.githubusercontent.com/25701854/156278860-0c0677ac-be21-4fe6-959e-a65e58363904.png)
<img width="233" alt="스크린샷 2022-03-02 오전 10 44 36" src="https://user-images.githubusercontent.com/25701854/156278861-9455ae44-41ab-40c5-8da1-22fa8cb07ceb.png">

2022-03-25 07:19 UTC, npbg commented on src/components/Button/Button.tsx
> +      case ButtonSize.L:
확인해보니 그렇네요. 이상하네요 어쩌다 2개나 이런 착각을 했지... 확인 감사합니다.

2022-03-28 02:08 UTC, inhibitor1217 requested changes

2022-03-28 02:08 UTC, inhibitor1217 commented on src/components/Button/Button.styled.ts
> +            ${({ foundation }) => foundation?.rounding?.round16};
여기 체크 해주세요.

![스크린샷 2022-03-28 오전 11 07 19](https://user-images.githubusercontent.com/25701854/160314500-edb3193d-6b20-41f9-bd3e-628102b5ac5b.png)
![스크린샷 2022-03-28 오전 11 07 24](https://user-images.githubusercontent.com/25701854/160314502-d28bef5a-6725-463f-8e55-a314097809a6.png)

2022-03-28 02:18 UTC, inhibitor1217 commented
패딩은 괜찮은 것 같아요.

2022-03-28 05:07 UTC, npbg commented on src/components/Button/Button.styled.ts
> +            ${({ foundation }) => foundation?.rounding?.round16};
ㅜ 감사합니다.

2022-03-28 06:49 UTC, inhibitor1217 approved these changes

2022-03-28 10:05 UTC, Seolhun reviewed
Button도 나름 Atomic한 Component인데, Text에 의존을 갖는게 의문이 남네요.

이러한 사이드이펙트로, 현재 Text의 bold는 font-weight 700(bold)입니다. Figma의 Button은 600(semi-bold)입니다.
https://developer.mozilla.org/ko/docs/Web/CSS/font-weight#%EC%9D%BC%EB%B0%98%EC%A0%81%EC%9D%B8_%EA%B0%80%EC%A4%91%EC%B9%98_%EC%9D%B4%EB%A6%84_%EB%A7%A4%ED%95%91

Size 관련 함수가 너무 분리되어있어서 개선되어도 좋을것 같네요.

2022-03-28 10:08 UTC, Seolhun commented
그리고, 현재 작업중이신 button 브랜치를 최신 next-v1으로 rebase 하신 후에
Testing.stories를 확인해주세요. 그리고, snapshot 테스트를 추가해주세요~

2022-03-28 10:12 UTC, npbg commented on src/components/Button/Button.styled.ts
> +  [ButtonSize.XL]: 2,
> Button도 나름 Atomic한 Component인데, Text에 의존을 갖는게 의문이 남네요.
> 
> 이러한 사이드이펙트로, 현재 Text의 bold는 font-weight 700(bold)입니다. Figma의 Button은 600(semi-bold)입니다. https://developer.mozilla.org/ko/docs/Web/CSS/font-weight#%EC%9D%BC%EB%B0%98%EC%A0%81%EC%9D%B8_%EA%B0%80%EC%A4%91%EC%B9%98_%EC%9D%B4%EB%A6%84_%EB%A7%A4%ED%95%91
> 
> Size 관련 함수가 너무 분리되어있어서 개선되어도 좋을것 같네요.

Button 내부의 content 들을 사용처에서 입력하게 하는 것 외에는 Text 와의 의존성을 배제하기 힘들 것 같긴 합니다.
여태 버튼 typo의 bold 값이 피그마에서 나온 것과 다른채로 계속 있었던 것 같은데, Text 의 bold 와 Button 의 bold 값이 다른 것이 의도된건진 확인해보겠습니다.

2022-03-28 10:12 UTC, npbg commented
> Button도 나름 Atomic한 Component인데, Text에 의존을 갖는게 의문이 남네요.
> 
> 이러한 사이드이펙트로, 현재 Text의 bold는 font-weight 700(bold)입니다. Figma의 Button은 600(semi-bold)입니다. https://developer.mozilla.org/ko/docs/Web/CSS/font-weight#%EC%9D%BC%EB%B0%98%EC%A0%81%EC%9D%B8_%EA%B0%80%EC%A4%91%EC%B9%98_%EC%9D%B4%EB%A6%84_%EB%A7%A4%ED%95%91
> 
> Size 관련 함수가 너무 분리되어있어서 개선되어도 좋을것 같네요.

Button 내부의 content 들을 사용처에서 입력하게 하는 것 외에는 Text 와의 의존성을 배제하기 힘들 것 같긴 합니다.
여태 버튼 typo의 bold 값이 피그마에서 나온 것과 다른채로 계속 있었던 것 같은데, Text 의 bold 와 Button 의 bold 값이 다른 것이 의도된건진 확인해보겠습니다.

2022-03-28 10:15 UTC, npbg commented on src/components/Button/Button.styled.ts
> +  [ButtonSize.XL]: 2,
Button 의 내부 content 에 text 만 있는 경우가 있고, 이 경우에도 Button 내 Text 의 경우 해당 padding 을 갖고 있습니다.

2022-03-28 11:08 UTC, Seolhun commented
넵, 이부분 확인해주시고 수정하면 좋을것 같아요~

2022-03-30 11:36 UTC, quino0627 approved these changes
버튼 font-weight 제외하고 확인했습니다

2022-03-31 03:56 UTC, npbg commented
Typography 의 bold 옵션 시 font-weight: 600 이 맞다고 합니다. Typography 로 수정하는 작업 별도 PR로 올리겠습니다.

2022-03-31 03:57 UTC, merged

2022-03-31 04:06 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.106 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.106)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.106)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: