Select 컴포넌트 구현을 button 엘리먼트로 변경 및 디자인 최신화
channel-io/bezier-react pull request #725
Opened 2022-02-18 08:24 UTC by sungik-choi

# Summary

fix #700, fix #708

- `Select` 컴포넌트 구현을 `button` 엘리먼트로 변경합니다 
- 인풋 컴포넌트(`TextField`, `TextArea`, `Select`) read-only 상태의 디자인 변경사항을 적용합니다.

# Details

- `Trigger` 의 엘리먼트 타입을 `button` 으로 변경. 키보드 포커싱이 가능해져, 엔터키를 통해 드롭다운을 열고 닫을 수 있게 됩니다
- read-only 상태의 배경 색상과 텍스트 색상 변경
- 스타일링 방식을 최대한 Native Selector를 사용하도록 리팩토링
- 일관성을 가지도록 변수명 리팩토링

## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)
### macOS
- [x] Chrome - Blink
- [x] Edge - Blink
- [x] Safari - WebKit : Safari의 버그로 버튼 키보드 포커스가 되지 않습니다.
- [x] Firefox - Gecko (Option)

# References

- [Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=0%3A1)

2022-02-18 10:37 UTC, aooen approved these changes

2022-02-21 02:03 UTC, inhibitor1217 requested changes
Select readOnly = true일 때 click / keyboard 를 통해 focus가 가능합니다.

2022-02-21 02:09 UTC, sungik-choi commented
> Select readOnly = true일 때 click / keyboard 를 통해 focus가 가능합니다.

기존에도 포커스가 되었는데, `:focus` 상태일 때 스타일이 지정되어있지 않아서 시각적으로 표시가 안되고 있었습니다.
[MDN - HTML attribute: readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly) 문서를 보면, readonly 상태일 때도 포커스는 가능한 게 일반적인 UX 같아요.

2022-02-21 03:23 UTC, inhibitor1217 approved these changes

2022-02-22 02:47 UTC, CHEWCHEWW approved these changes

2022-02-22 02:47 UTC, merged

2022-02-22 02:57 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.96 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.96)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.96)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: