Tree-shakable한 Icon 컴포넌트 구현
channel-io/bezier-react pull request #729
Opened 2022-02-22 12:20 UTC by sungik-choi

# Summary

사용처에서 Tree-shaking이 가능한 Icon 컴포넌트를 구현합니다.
아이콘이 모두 변경되어, 변경사항이 많습니다. 커밋별로 확인해주세요!

# Details

### AS-IS

```tsx
import { Icon } from '@channel.io/bezier-react' 

<Icon name="all" color="txt-black-dark" />
```

현재는 사용처에서 `name` 속성에 아이콘 이름을 넣으면 `Icon` 컴포넌트 내부에서 generated된 아이콘 객체에서 `IconName` 을 key로 아이콘을 찾아서 렌더하는 방식으로 구현되어 있습니다. 빌드 타임에 어떤 아이콘이 사용될지 알 수 없기 때문에, `Icon` 컴포넌트를 사용하면 사용하지 않는 모든 아이콘이 번들링된 파일에 포함됩니다.

### TO-BE

```tsx
import { AllIcon } from '@channel.io/bezier-react' 

<AllIcon color="txt-black-dark" />
```

`IconName` 으로 아이콘을 "찾아서" 렌더하는 대신, 사용처에서 아이콘을 "직접" 가져와서 사용합니다. 어떤 아이콘을 사용할 지 빌드 타임에 알 수 있기 때문에, 번들링된 파일에 불필요한 아이콘이 포함되지 않습니다.

아래와 같은 점들을 고려했습니다.
- svg 에셋명에 `icon` suffix를 추가합니다. svgr cli를 통하면 svg 에셋명이 파스칼 케이스화 되어 컴포넌트명이 됩니다. 기존엔 `IconName` 을 통해 generated된 icons 객체에서 찾아서 컴포넌트를 그렸기에 문제가 발생하지 않았지만, 개별 컴포넌트로 사용처에서 import해서 사용할 경우 문제가 발생합니다. `icon` suffix가 없을 경우 명시적이지 않기도 하거니와, 무엇보다도 다른 컴포넌트와 이름이 겹치게 됩니다. (예를 들어, `Typography` 라는 아이콘이 있습니다)
- 다만 기존의 `Icon` 을 사용하는 사용처에선 문제가 발생하면 안되기 때문에, 기존에 사용하던 `IconName` 은 변하지 않도록 했습니다.

### Svgr 라이브러리 업데이트
- v5 -> v6 마이그레이션을 함께 진행했습니다.
- https://react-svgr.com/docs/migrate/ 문서를 참고하였으며, cli template 스크립트(`icon-template`)에만 변경사항이 있습니다.

### 그 외
- 기존 `Icon` 컴포넌트는 `LegacyIcon` 으로 이름을 변경하고 `Icon/legacy` 디렉터리 아래로 이동했습니다.

## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.

> 채널 데스크에서 빌드 후 테스트했으며 문제 없는 걸 확인했습니다.

### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)
### macOS
- [x] Chrome - Blink
- [x] Edge - Blink
- [x] Safari - WebKit
- [x] Firefox - Gecko (Option)

# References

- https://react-svgr.com/docs/migrate/

2022-02-22 12:26 UTC, dinohan commented
`icon`이 suffix가 아니라 prefix로 붙는 건 어떤가요?
인텔리센스에 이점이 있을 것 같아서요.

2022-02-22 12:37 UTC, sungik-choi commented
> `icon`이 suffix가 아니라 prefix로 붙는 건 어떤가요? 인텔리센스에 이점이 있을 것 같아서요.

저는 인텔리센스의 이점보다 더 일반적인 네이밍 방식이 더 좋다고 생각했어요.

2022-02-23 02:54 UTC, quino0627 reviewed
icon asset이 추가될때마다 수동으로 -icon postfix를 붙혀주어야 하는걸까요?

2022-02-23 03:02 UTC, sungik-choi commented
> icon asset이 추가될때마다 수동으로 -icon postfix를 붙혀주어야 하는걸까요?

지금 당장은 그렇고, 추후에 피그마에서 바로 가져온 후 suffix를 붙이는 방식으로 변경해야할 거 같아요

2022-02-23 03:10 UTC, quino0627 commented on src/components/Icon/createIcon.tsx
> +      as={iconFn}
오 as가 컴포넌트를 넣어도 되는군요

2022-02-23 03:10 UTC, quino0627 commented
> > icon asset이 추가될때마다 수동으로 -icon postfix를 붙혀주어야 하는걸까요?
> 
> 지금 당장은 그렇고, 추후에 피그마에서 바로 가져온 후 suffix를 붙이는 방식으로 변경해야할 거 같아요

스크립트로 해결할 수 있을까 싶어 물어봤는데 피그마 직접 연결하는거면 🆗

2022-02-23 03:12 UTC, quino0627 approved these changes

2022-02-23 03:14 UTC, aooen approved these changes

2022-02-23 03:56 UTC, guswnsxodlf requested changes

2022-02-23 03:56 UTC, guswnsxodlf commented on src/components/Icon/generated/All.tsx
> +import { SVGProps } from 'react'
```import type ...```
여기는 데스크랑 달라서 보통 어떻게 하는지 모르겠네요

2022-02-23 03:56 UTC, guswnsxodlf commented on scripts/icon-index-template.js
> +  return basename.search(POSTFIX_REGEX) !== -1
`basename.endswith` 혹은 `POSTFIX_REGEX`에 끝을 알리는 `$`를 붙이면 더 좋을 것 같네요

2022-02-23 03:57 UTC, guswnsxodlf commented on scripts/icon-index-template.js
> +  return basename.search(POSTFIX_REGEX) !== -1
앗 SUFFIX로 바꾸셨으니 반대로..

2022-02-23 03:59 UTC, sungik-choi commented on src/components/Icon/generated/All.tsx
> +import { SVGProps } from 'react'
이 부분은 SVGR이 자동으로 생성해주는 코드라 수정하긴 어려울 거 같아요

2022-02-23 04:03 UTC, sungik-choi commented on scripts/icon-index-template.js
> +  return basename.search(POSTFIX_REGEX) !== -1
`endswith()` 메서드 좋네요 👍

2022-02-23 04:05 UTC, sungik-choi commented on src/components/Icon/createIcon.tsx
> +      as={iconFn}
넹 기존에도 이 방식으로 아이콘을 그려주고 있었어요

2022-02-23 04:50 UTC, inhibitor1217 reviewed
breaking change인데 바로 마이그레이션할 룸이 있을까요?
Icon export name 변경 없이 deprecated로 처리하면 되지 않을까요?

2022-02-23 04:50 UTC, inhibitor1217 commented on src/components/Icon/Icon.tsx
> +}: IconProps & Pick<BezierComponentProps, 'as'>) {
as를 BezierComponentProps에 포함해주세요. IconProps가 Omit<BezierComponentProps, 'as'> 를 extend하고 있네요.

2022-02-23 04:53 UTC, sungik-choi commented
> breaking change인데 바로 마이그레이션할 룸이 있을까요? Icon export name 변경 없이 deprecated로 처리하면 되지 않을까요?

기존 `Icon` 은 그대로 사용가능해요. `LegacyIcon as Icon` 으로 export됩니다. 새로 생긴 `Icon` 은 export되지 않고 `createIcon` 함수를 통해 개별 아이콘을 생성하는 데만 사용돼요.

2022-02-23 05:01 UTC, sungik-choi commented on src/components/Icon/Icon.tsx
> +}: IconProps & Pick<BezierComponentProps, 'as'>) {
이 컴포넌트 이름을 `BaseIcon` 정도로 변경하는 게 좋겠네요. 이 컴포넌트는 createIcon을 통해서 Icon을 생성하는 데만 쓰이는데, 그 과정에서 as 속성이 필요해 이런 식으로 지정해줬어요.

2022-02-23 05:12 UTC, inhibitor1217 approved these changes

2022-02-23 05:13 UTC, sungik-choi commented on src/components/Icon/legacy/LegacyIcon.tsx
> +const LegacyIcon = memo(({
기존 컨벤션처럼 일반 function 사용 후 `export default memo(Component)` 하게 되면 빌드 후 deprecated 주석이 제대로 적용이 안되어서 화살표 함수로 변경했습니다.

2022-02-23 05:15 UTC, guswnsxodlf approved these changes

2022-02-23 06:08 UTC, dinohan approved these changes

2022-02-23 06:34 UTC, sungik-choi commented on src/components/Icon/Icon.tsx
> +}: IconProps & Pick<BezierComponentProps, 'as'>) {
a764958

2022-02-23 06:37 UTC, merged

2022-02-23 06:47 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.99 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.99)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.99)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: