add BaseModal, Modal and ConfirmModal
channel-io/bezier-react pull request #734
Opened 2022-02-23 09:56 UTC by Seolhun

# Summary

Modal Components를 추가합니다.

기존 Desk에서 사용하는것에서 개선/변경하였습니다.
스토리북과 테스트코드도 함께 개선/추가되었습니다.

# Details

- BaseModal
  - Modal
    - ConfirmModal

위와 같은 의존성관계를 가집니다.

BaseModal은 ModalWrapper, ModalBackground, Modal 3가지 구조를 가집니다.
Modal은 BaseModal 내에 Modal__Header, Body, Footer로 3개의 하위 Component를 구현합니다.
ConfirmModal은 Modal을 기반으로, Enter event를 기본적으로 갖도록 변경하였습니다.

## Browser Compatibility

OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)

### macOS
- [x] Chrome - Blink
- [ ] Edge - Blink
- [ ] Safari - WebKit
- [ ] Firefox - Gecko (Option)

# References
#727

2022-02-23 10:01 UTC, Seolhun commented
CI는 정상으로 만들어놓을게요. 로컬에서 commit 할 때 문제없었는데, 이유를 찾아봐야겠네요.

2022-02-24 02:09 UTC, Seolhun commented
- fix Modal snapshot test error
- add Modal.Header available typography key props

2022-02-24 02:31 UTC, Seolhun commented
- rebase를 계속하다보니 snapshot error가 발생하여 이를 수정

2022-02-28 02:34 UTC, aooen approved these changes

2022-02-28 07:26 UTC, sungik-choi reviewed
`Modal` 컴포넌트의 코드상 구현은 아래와 같은데,

```mermaid
flowchart BT
ModalHeader --> Modal
ModalBody --> Modal
ModalFooter --> Modal
children*HeaderText --> ModalHeader
CloseIcon --> ModalHeader
children*BodyText --> ModalBody
children*FooterText --> ModalFooter
```

피그마상 구현은 아래와 같습니다.

```mermaid
flowchart BT
Contents --> Modal
Actions --> Modal
Title --> Contents
Desc --> Contents
TitleSubtitle --> Title
TitleText  --> TitleSubtitle
Icon*HelpIcon --> TitleSubtitle
CancelIcon --> Title
LeftSide --> Actions
RightSide*Buttons --> Actions
```

컴포넌트명이 중요하진 않고, 모달 컴포넌트를 구성하는 방식이 중요하다고 생각해요. 
현재 기존 데스크의 구현 방식대로면 둘 간의 구성 방식 차이가 다소 있는 거 같아요.
둘의 구현이 100% 일치할 수는 없겠지만, 어느 정도는 일치하는게 좋을 거 같아요!

2022-03-01 22:52 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.types.tsx
> +   * @deprecated
이 부분은 제가 놓친것 같아요. 사용해야하는 props입니다.

2022-03-01 22:55 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +Modal.Footer = ModalFooter
두 방식에는 차이가 있다고 생각합니다.
특히, Context를 공유하여 Close가 Header에 의존됩니다. 그런 부분에 대한 표현이 부족해진다고 생각합니다.

통일성이 필요하다면 변경하는 것에는 어려움이 없습니다.

2022-03-02 00:39 UTC, Seolhun commented
> "`Modal` 컴포넌트의 코드상 구현은 아래와 같은데"에 대한 답변

![Screen Shot 2022-03-02 at 9 30 50 AM](https://user-images.githubusercontent.com/16330024/156271891-e501a890-cf70-4e91-bd00-929814b0956a.png)
![Screen Shot 2022-03-02 at 9 31 15 AM](https://user-images.githubusercontent.com/16330024/156271937-276be35f-c707-4865-864c-ffb6e385aebb.png)
![Screen Shot 2022-03-02 at 9 31 19 AM](https://user-images.githubusercontent.com/16330024/156271941-619b9bc8-e1dc-41df-a477-b8285e838540.png)
![Screen Shot 2022-03-02 at 9 31 22 AM](https://user-images.githubusercontent.com/16330024/156271944-2f2ec4ce-33c0-4a84-bbe0-d3f5b0733302.png)

2022-03-02 02:00 UTC, sungik-choi commented on src/components/Modals/Modal/Modal.tsx
> +Modal.Footer = ModalFooter
> 특히, Context를 공유하여 Close가 Header에 의존됩니다. 그런 부분에 대한 표현이 부족해진다고 생각합니다.

저도 공감합니다. 이 부분에 있어선 객체에 담아 export 하는 방식이 분명히 이점이 있다고 생각해요. 다만, 저는 이 이점보다 저희 라이브러리의 전체적인 방식의 통일성을 맞추는게 사용자의 예측 가능성을 높여줄 수 있다는 점에서 더 좋다고 생각했어요.

2022-03-02 02:02 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +Modal.Footer = ModalFooter
이 부분은 첫 Comment 피그마와 구조를 맞추기 위한 작업변경으로
Header, Body, Footer 모두 제거할 예정입니다.

2022-03-02 02:05 UTC, inhibitor1217 commented on src/components/Modals/BaseModal/BaseModal.styled.ts
> +  background-color: ${({ foundation }) => foundation?.theme?.['bg-white-normal']};
-> bg-white-high

2022-03-02 02:14 UTC, inhibitor1217 commented on src/components/Modals/Modal/Modal.styled.ts
> +export const CloseIconButton = styled(Button)``
![스크린샷 2022-03-02 오전 11 13 41](https://user-images.githubusercontent.com/25701854/156281607-e5d48b29-0452-40ba-857f-2d66e37de33c.png)

시안에서 close button은 content edge로부터 6px씩 더 가깝습니다.

2022-03-02 02:19 UTC, inhibitor1217 commented on src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
> +  onConfirm: () => void
타입을 () => Promise<void> 로 하고, `onConfirm().then(onClose).catch(noop)` 와 같이 처리하면 비동기 confirm 동작을 지원합니다.

2022-03-02 02:23 UTC, Seolhun commented on src/components/Modals/Modal/Modal.styled.ts
> +export const CloseIconButton = styled(Button)``
넵 이부분 18px 로 고치고 Title에 6px을 추가하였습니다.

2022-03-02 02:37 UTC, Seolhun commented on src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
> +  onConfirm: () => void
Component의 props를 Promise로 하는 경우는 잘 보지 못했습니다.

https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L45
Antd를 좋아하진 않지만, UI에 맞게 구성되는게 기본인것 같아요.

2022-03-02 02:45 UTC, Seolhun commented
> * 여러 element에 붙는 `testId`를 prop interface에 추가하여 외부(= 외부 테스트 코드)에서 주입 가능하도록 해주세요.
@inhibitor1217 

```tsx
// Select.tsx

function Select({
  testId = SELECT_CONTAINER_TEST_ID,
  triggerTestId = SELECT_TRIGGER_TEST_ID,
  triggerTextTestId = SELECT_TRIGGER_TEXT_TEST_ID,
  dropdownTestId = SELECT_DROPDOWN_TEST_ID,
  // ...
})
```
Select를 보면 위와 같이 구성되기를 원하시는게 맞나요?
의문은 Select에는 해당 값들이 interface에 선언이 되어있지 않은데, 이를 선언해서 사용되었으면 하는것일까요?

2022-03-02 03:03 UTC, inhibitor1217 commented
Select에도 testId 선언이 되어 있습니다.

```
// Select.types.ts

interface SelectProps extends
  BezierComponentProps,  // <- testId
  ChildrenProps,
  SizeProps<SelectSize>,
  SideContentProps<IconName | React.ReactNode, IconName | React.ReactNode>,
  AdditionalTestIdProps<['trigger', 'triggerText', 'dropdown']>, // <- triggerTestId, triggerTextTestId, dropdownTestId
  AdditionalStylableProps<'dropdown'>,
  AdditionalColorProps<['icon', 'text']>,
  FormComponentProps,
  SelectOptions {}
```

2022-03-02 04:12 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +Modal.Footer = ModalFooter
제거완료.

2022-03-02 04:12 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.types.tsx
> +   * @deprecated
제거완료.

2022-03-02 04:13 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    targetElement = document.body,
테스트코드와 함께 변경완료.

2022-03-02 04:13 UTC, Seolhun commented on src/components/Modals/Modal/Modal.types.tsx
> +/* eslint-disable no-restricted-imports */
참고하여 작성하긴했습니다.

2022-03-02 04:27 UTC, aooen approved these changes

2022-03-02 04:31 UTC, Seolhun commented
이번 Commit에서 Modal을 피그마의 구조와 최대한 맞춰 변경하였습니다.
```mermaid
flowchart BT
Contents --> Modal
Actions --> Modal
Title --> Contents
Desc --> Contents
TitleSubtitle --> Title
TitleText  --> TitleSubtitle
LeftSide --> Actions
RightSide*Buttons --> Actions
```

2022-03-02 05:11 UTC, Tanney-102 commented on src/components/Modals/ConfirmModal/ConfirmModal.tsx
> +  }, [onKeyDown])
혹시 아래 onKeyDownWithConfirm에서 바로 onKeyDown을 사용하면 안되는 이유가 있을까요??

2022-03-02 06:18 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +          </Styled.TitleAndSubTitle>
testId는 바뀐게 맞는것 같아요. 수정이 필요하겠네요.
props 그대로 사용하는거라서 굳이 값이 잘 렌더링되었는지를 테스트할 필요는 없다고 생각했습니다.

2022-03-02 06:21 UTC, Seolhun commented on src/components/Modals/ConfirmModal/ConfirmModal.tsx
> +  }, [onKeyDown])
Confirm과 onKeyDown 이벤트를 명확하게 분리하고자 했던것입니다.
이유는 없습니다.

2022-03-02 06:35 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +          </Styled.TitleAndSubTitle>
subTitle 과 testId 이슈는 수정했습니다.

2022-03-03 07:25 UTC, sungik-choi commented on src/components/Modals/Modal/Modal.tsx
> +    rightContent,
prop명이 덜 직관적인 거 같아요. `leftContent`, `rightContent` prop이 `ModalAction` 의 prop일 때는 이상하지 않은데, `Modal` 의 prop일 경우엔 어디에 들어갈 속성인지 명확하게 와닿지가 않는 거 같아요. 

`leftActionContent` 같은 이름으로 변경할 수도 있고, 아예 이전처럼 내부 컴포넌트들에게 각자 책임을 나눠서 개별 export 하는 방식도 좋을 거 같아요. 개인적으론 후자가 더 좋아보여요. Modal 하위 컴포넌트들의 prop을 모두 Modal 컴포넌트를 통해 전달하게 되면 prop의 갯수가 너무 많아질 거 같아요.

```tsx
<Modal>
  <ModalContent title={...} subTitle={...}>{...}</ModalContent>
  <ModalAction />
</Modal>
```

2022-03-03 07:37 UTC, Seolhun commented on src/components/Modals/Modal/Modal.tsx
> +    rightContent,
- leftContent, rightContent로 정의된 interface가 공용인것 같아서 받았는데, 변경하도록 할게요.
- title에 주석에도 적었다시피 아이콘을 넣지 않은 이유가 복잡도때문입니다.
- Action이 없는 모달이 없기 때문에 굳이 분리할 필요를 느끼지 못했습니다. 사실 후자처럼 가려면 초기 디자인되었떤 Header, Body, Footer도 괜찮았던것 같습니다. 왜냐하면, 그 안에서 Title, SubTitle만 더 추가해주었어도 되었기 때문입니다. 세부적으로 자유도가 높은 UI를 원한다면 후자가 낫고, 정해진 디자인 스펙을 따르려면 전자가 나을것 같아보여요.

2022-03-03 07:51 UTC, inhibitor1217 commented on src/components/Modals/Modal/Modal.styled.ts
> +export const CloseIconButton = styled(Button)``
close button의 right edge로부터의 거리도 18px가 되어야 해요. 지금은 top edge로부터의 거리만 수정되었네요

2022-03-03 07:55 UTC, inhibitor1217 commented on src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
> +  onConfirm: () => void
onConfirm을 `() => PromiseLike<void>`로 하면 promise가 아닌 곳의 문제는 해결됩니다.
modal에서 form submit 시에 modal이 닫혀버리고 나서 실패 토스트가 뜨는 UX가 좋지 않다고 생각했습니다.

2022-03-03 08:18 UTC, sungik-choi commented on src/components/Modals/Modal/Modal.tsx
> +    rightContent,
> Action이 없는 모달이 없기 때문에 굳이 분리할 필요를 느끼지 못했습니다. 사실 후자처럼 가려면 초기 디자인되었떤 Header, Body, Footer도 괜찮았던것 같습니다. 왜냐하면, 그 안에서 Title, SubTitle만 더 추가해주었어도 되었기 때문입니다. 세부적으로 자유도가 높은 UI를 원한다면 후자가 낫고, 정해진 디자인 스펙을 따르려면 전자가 나을것 같아보여요.

저도 동의합니다. 엄격함과 유연함 사이의 균형을 잘 맞춰야될 거 같아요. 구현해주신대로 우선 적용하고 추후에 유연함이 더 필요하다고 생각되면 변경해도 괜찮을 거 같아요.

2022-03-08 04:12 UTC, Seolhun commented on src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
> +  onConfirm: () => void
실패했을 경우 event 전파를 막으면되는것으로 보입니다.
onConfirm의 event를 넘겨주는 방식이 구현에 적합해보입니다.
onConfirm(e: KeyboardEvent)

2022-03-08 04:44 UTC, Seolhun commented on src/components/Modals/Modal/Modal.styled.ts
> +export const CloseIconButton = styled(Button)``
close-button의 margin - 값을 주는것으로 변경합니다.

2022-03-08 04:46 UTC, inhibitor1217 commented on src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
> +  onConfirm: () => void
네 일단 이 항목은 resolved로 둘께요!

2022-03-08 09:30 UTC, Seolhun commented
- default export로 변경
- ModalContext, ModalAction export로 변경
- Closebutton의 margin-top, right: -6px 추가

2022-03-08 09:31 UTC, Tanney-102 approved these changes

2022-03-10 03:02 UTC, inhibitor1217 approved these changes

2022-03-10 05:13 UTC, sungik-choi approved these changes

2022-03-11 01:39 UTC, Seolhun commented
- [ ] backdropClassName에 대한 좋은 아이디어를 받습니다. 내부에 대한 props를 어떻게 전달해야할지 고민입니다.
- [ ] Modal Title과 Description에 Typography 적용을 어떻게하면 좋을까요?

2022-03-11 03:47 UTC, Seolhun commented
- ModalContent에 ModalTitleText라는 Component를 추가했습니다. titleSize Props를 통해 15,24를 받게하였습니다.
- attrs로 적용하기에는 타입확장이 되지 않아, useMemo로 버튼과 똑같이 처리했습니다.

2022-03-11 03:58 UTC, aooen approved these changes

2022-03-14 06:05 UTC, inhibitor1217 approved these changes
데스크에 있던 BaseModal의 backdropClassName은 사용하는 곳이 한 곳밖에 없어서, (OtmSuccessModal인 것 같네요) deprecated로 두고 간단한 싱크 후 삭제해보아도 좋을 것 같습니다!

OtmSuccessModal 보면 backdrop에 opacity: 0 줘서 투명하게 만들고 있는데 modal의 좋은 용법인 것 같지도 않구요 😅

2022-03-21 08:37 UTC, guswnsxodlf requested changes
전체적으로 type import는 import type 을 붙여주시면 좋을 것 같습니다.

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +import { BaseModalProps } from './BaseModal.types'
```suggestion
import type { BaseModalProps } from './BaseModal.types'
```

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    return function noop() { }
이 줄은 없애도 되지 않을까요?

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    autoFocus,
이게 deps에 있다면 모달은 이미 떠있는 상태에서 (show가 true), autoFocus가 false에서 true로 바뀔 때에도 focus가 될텐데 의도하신걸까요?

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/Modal/Modal.types.tsx
> +   * (@sol) The reason it is "React.ReactNode" rather than "string" is to avoid increasing complexity by adding icon props.
어떻게 복잡도가 증가하는건지 잘 이해가 안되는데 설명해주실 수 있나요?

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/ConfirmModal/ConfirmModal.tsx
> +  const handleOnKeyDown = useCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
```suggestion
  const handleKeyDown = useCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
```
보통 on{event} 에 대응하는 함수를 작성할 때 handle{event}로 네이밍 합니다.

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/Modal/ModalContext.ts
> +import { ModalContextValue } from './Modal.types'
```suggestion
import type { ModalContextValue } from './Modal.types'
```

2022-03-21 08:37 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +  const onCloseModalByEsc = useCallback((e: KeyboardEvent) => {
```suggestion
  const handleKeydown = useCallback((e: KeyboardEvent) => {
```
handleKeydown이 더 적합해보입니다!

2022-03-21 08:41 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.tsx
> +  const onCloseModalByEsc = useCallback((e: KeyboardEvent) => {
여기는 onKeydown을 handle하지는 않습니다. esc만 handle합니다.

2022-03-21 08:41 UTC, Seolhun commented on src/components/Modals/Modal/ModalContext.ts
> +import { ModalContextValue } from './Modal.types'
네, 자동으로 안되네요. 변경할게요~

2022-03-21 08:42 UTC, Seolhun commented on src/components/Modals/Modal/Modal.types.tsx
> +   * (@sol) The reason it is "React.ReactNode" rather than "string" is to avoid increasing complexity by adding icon props.
icon에 대한 event를 props에 넣어줘야되는지가 의문입니다.
그냥 children으로 합성하게 두면 그 사용처에서 구현하게 둘 수 있다는 이야기입니다.
icon을 안쓰는 곳도 있을텐데, 그걸 굳이 세세하게 정의할 필요가 없다는 이야기입니다.

2022-03-21 08:45 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    return function noop() { }
lint 경고가 떠서 undefined를 return하는 방법도 있습니다.

2022-03-21 08:45 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    autoFocus,
젤로의 의도는 mount때만 실행이 되어야하므로 deps에 autoFucus를 빼자는 이야기일까요?

2022-03-21 08:47 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    autoFocus,
일부러 넣으신게 아니라면 빼는 것이 더 자연스럽지 않을까 생각합니다~

2022-03-21 08:48 UTC, guswnsxodlf commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    return function noop() { }
함수가 아닌 undefined을 리턴하는 것이 더 좋을 것 같습니다

2022-03-22 01:36 UTC, Seolhun commented on src/components/Modals/BaseModal/BaseModal.tsx
> +    autoFocus,
일부러 넣은건데, autoFocus를 중간에 바꾸는것을 보장해줄 필요가 없어서 젤로말대로 빼는게 낫겠네요.

2022-03-22 01:49 UTC, Seolhun commented
- Event 네이밍 on 제거 반영 (젤로 리뷰)
- import module에 type 추가되지 않은것 반영  (젤로 리뷰)
- autoFocus를 mount된 이후에 값을 바뀌어도 적용되지 않게 번경 (젤로 리뷰)

2022-03-22 03:44 UTC, guswnsxodlf approved these changes

2022-04-12 07:04 UTC, Seolhun commented
@sungik-choi Room 되면 리뷰 부탁드립니다. 에드 리뷰 받고 머지하려고합니다.

2022-04-12 12:23 UTC, sungik-choi commented
> @sungik-choi Room 되면 리뷰 부탁드립니다. 에드 리뷰 받고 머지하려고합니다.

넵, 릴리즈 후에 1순위로 챙겨보겠습니다!

2022-04-15 06:50 UTC, sungik-choi approved these changes

2022-04-18 03:04 UTC, merged

2022-04-19 02:40 UTC, ch-builder commented
:tada: This PR is included in version 1.0.0-next-v1.112 :tada:

The release is available on:
- [npm package (@next-v1 dist-tag)](https://www.npmjs.com/package/@channel.io/bezier-react/v/1.0.0-next-v1.112)
- [GitHub release](https://github.com/channel-io/bezier-react/releases/tag/v1.0.0-next-v1.112)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: