Switch 컴포넌트 구현이 Figma 명세를 따르도록 수정
channel-io/bezier-react pull request #848
Opened 2022-07-04 05:19 UTC by Dogdriip

# Summary

- Forms의 `Switch` 컴포넌트 구현이 Figma 명세를 따르도록 수정합니다.

# Details

> Closes #840

- [x] BREAKING CHANGE: `size` prop은 더 이상 `number`형이 아닌, 새로 정의한 `SizeVariant` enum 타입을 사용합니다.
  ```ts
  export enum SwitchSize {
    M = 'm',
    S = 's',
  }
  ```
- [x] `Switch` 컴포넌트의 `width`, `height`, `disabled = true` 시의 `opacity`가 명세에 맞게 변경됩니다.
- [x] `border-radius`를 `foundation.rounding`을 사용합니다.
- [x] `Switch` 핸들 컴포넌트의 `width`, `height` 및 absolute 위치(padding)이 명세에 맞게(2px -> 3px) 변경됩니다.

## Browser Compatibility
OS / Engine 호환성을 반드시 확인해주세요.
### Windows
- [ ] Chrome - Blink
- [ ] Edge - Blink
- [ ] Firefox - Gecko (Option)
### macOS
- [x] Chrome - Blink
- [ ] Edge - Blink
- [ ] Safari - WebKit
- [ ] Firefox - Gecko (Option)

# References

- [Figma Switch](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=3263%3A131)

2022-07-04 06:38 UTC, inhibitor1217 requested changes

2022-07-04 06:38 UTC, inhibitor1217 commented on packages/bezier-react/src/components/Forms/Switch/index.ts
> +import type { SwitchSize } from './Switch.types'
SwitchSize enum을 type export만 하면, 사용처에서 값을 가져다가 사용할 수 없습니다.

2022-07-04 06:51 UTC, Dogdriip commented on packages/bezier-react/src/components/Forms/Switch/index.ts
> +import type { SwitchSize } from './Switch.types'
d8f7292b 에서 수정합니다. https://github.com/channel-io/bezier-react/blob/next-v1/packages/bezier-react/src/components/ProgressBar/index.ts#L8-L9 여기도 고쳐야겠네요 😅

2022-07-04 07:31 UTC, inhibitor1217 approved these changes

2022-07-05 05:00 UTC, sungik-choi approved these changes
마이그레이션이 필요하겠네요

2022-07-07 07:48 UTC, sungik-choi commented
리베이스 후 changeset 추가 부탁드려요!

2022-07-07 08:31 UTC, sungik-choi commented
Changelog는 영어로 작성해주실 수 있을까요?
제가 관련해서 따로 가이드 만들어두겠습니다 🙏

2022-07-08 04:57 UTC, Seolhun approved these changes
다른 이야기지만, Switch ref가 inputElement면 좋을것 같은데 아쉽네요.

2022-07-08 05:00 UTC, Dogdriip commented
> 다른 이야기지만, Switch ref가 inputElement면 좋을것 같은데 아쉽네요.

관련해서 #711 에 이미 이슈화되고 어사인받은 게 있어서 염두에 두고 있습니다! 추후에 bezier 전반적으로 접근성 방향성이 잡히고 작업 시작되면 시도해보려 합니다 💪

2022-07-08 05:00 UTC, merged